# -*- coding: utf-8 -*-
"""add.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCUU1hP5o-t2AOqA8uR7V3IDzJDfyuWM
"""

import streamlit as st
import sqlite3


DB_NAME = "SQLite.db"

def init_db():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS addition_memory (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            num1 INTEGER,
            num2 INTEGER,
            result INTEGER
        )
    """)
    conn.commit()
    conn.close()

def save_to_db(num1, num2, result):
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO addition_memory (num1, num2, result) VALUES (?, ?, ?)",
        (num1, num2, result)
    )
    conn.commit()
    conn.close()

def get_history():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT num1, num2, result FROM addition_memory ORDER BY id DESC")
    rows = cursor.fetchall()
    conn.close()
    return rows

def clear_history():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("DELETE FROM addition_memory")
    conn.commit()
    conn.close()


st.set_page_config(page_title="Addition App", layout="centered")
st.title("Addition App (SQLite + Streamlit)")

init_db()


num1 = st.number_input("Enter first number", step=1)
num2 = st.number_input("Enter second number", step=1)

if st.button("Add Numbers"):
    result = num1 + num2
    save_to_db(num1, num2, result)
    st.success(f"Sum = {result}")
    st.info("Result saved in SQLite memory")


st.subheader("History")
history = get_history()

if history:
    for n1, n2, res in history:
        st.write(f"{n1} + {n2} = {res}")
else:
    st.write("No history yet.")

# Clear history
if st.button("Clear History"):
    clear_history()
    st.warning("History cleared!")
